package cmd

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

var (
	initIdeaTmux          bool
	initIdeaTmuxAutostart string
	initCompletion        bool
)

var initCmd = &cobra.Command{
	Use:   "init <shell>",
	Short: "Print shell integration (add eval \"$(iwt init zsh)\" to .zshrc)",
	Long: `Print shell integration to stdout. Add to .zshrc:

  eval "$(iwt init zsh)"

This provides:

  Ctrl+O widget   repository picker that opens the selection in IDEA:
                  Enter opens the repository, Tab drills into its
                  worktrees; there Ctrl+N creates a worktree via iwt add
                  for a typed or picked branch, Ctrl+D removes the
                  highlighted one, Ctrl+X prunes merged ones, and
                  Ctrl+H/Esc goes back a level
  Ctrl+G widget   the same navigation, but cd's into the selection and
                  only navigates

Both widgets run the built-in inline picker (iwt pick). Override the
widget keys by setting IWT_OPEN_KEY / IWT_CD_KEY before the eval line.

--idea-tmux adds: inside IDEA's built-in terminal, attach to a tmux
session named after the current worktree, creating it when needed.

--idea-tmux-autostart <cmd> additionally runs <cmd> once in each freshly
created session, right before the first prompt (implies --idea-tmux).

--completion also registers the iwt command completion; the eval line
must then come after compinit in .zshrc (it is skipped silently when
compinit has not run).

Only zsh is supported.`,
	Args: cobra.ExactArgs(1),
	RunE: runInit,
}

func init() {
	initCmd.Flags().BoolVar(&initIdeaTmux, "idea-tmux", false, "attach IDEA's terminal to a per-worktree tmux session")
	initCmd.Flags().StringVar(&initIdeaTmuxAutostart, "idea-tmux-autostart", "", "command to run once in freshly created sessions (implies --idea-tmux)")
	initCmd.Flags().BoolVar(&initCompletion, "completion", false, "also register the iwt command completion (eval after compinit)")
	rootCmd.AddCommand(initCmd)
}

func runInit(cmd *cobra.Command, args []string) error {
	if args[0] != "zsh" {
		return fmt.Errorf("unsupported shell %q (only zsh is supported)", args[0])
	}
	var b strings.Builder
	b.WriteString(zshBase)
	if initIdeaTmux || initIdeaTmuxAutostart != "" {
		extra := ""
		if initIdeaTmuxAutostart != "" {
			extra = " -e IWT_TMUX_AUTOSTART=" + zshQuote(initIdeaTmuxAutostart)
		}
		fmt.Fprintf(&b, zshIdeaTmux, extra)
		b.WriteString(zshAutostartReceiver)
	}
	if initCompletion {
		// Embedded rather than eval'ing "iwt completion zsh" to avoid a
		// second iwt invocation per shell start. compdef only exists
		// once compinit has run, hence the guard.
		b.WriteString("\nif (( $+functions[compdef] )); then\n")
		if err := rootCmd.GenZshCompletion(&b); err != nil {
			return err
		}
		b.WriteString("fi\n")
	}
	fmt.Print(b.String())
	return nil
}

func zshQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

const zshBase = `# iwt zsh integration (generated by "iwt init zsh")

if [[ -o interactive ]]; then
  function iwt-open-widget() {
    iwt pick --open
    zle reset-prompt
  }
  zle -N iwt-open-widget
  bindkey "${IWT_OPEN_KEY:-^O}" iwt-open-widget

  function iwt-cd-widget() {
    local p
    p=$(iwt pick --cd) && [[ -n "$p" ]] && cd "$p"
    zle reset-prompt
  }
  zle -N iwt-cd-widget
  bindkey "${IWT_CD_KEY:-^G}" iwt-cd-widget
fi
`

// zshIdeaTmux attaches IDEA's terminal to a per-worktree tmux session.
// %s carries the optional autostart handoff (-e IWT_TMUX_AUTOSTART=...),
// applied only when a session is created.
const zshIdeaTmux = `
if (( $+commands[tmux] )) && [[ "$TERMINAL_EMULATOR" == "JetBrains-JediTerm" && -z "$TMUX" ]]; then
  _iwt_session="${${PWD:t}//./_}"
  if tmux has-session -t "=$_iwt_session" 2>/dev/null; then
    exec tmux attach-session -t "=$_iwt_session"
  else
    exec tmux new-session -s "$_iwt_session"%s
  fi
fi
`

// zshAutostartReceiver consumes IWT_TMUX_AUTOSTART once per session. The
// precmd hook defers the command until .zshrc has fully run, so the eval
// line can sit anywhere in it.
const zshAutostartReceiver = `
if [[ -n "$TMUX" && -n "$IWT_TMUX_AUTOSTART" ]]; then
  function _iwt-tmux-autostart() {
    add-zsh-hook -d precmd _iwt-tmux-autostart
    local cmd="$IWT_TMUX_AUTOSTART"
    unset IWT_TMUX_AUTOSTART
    tmux set-environment -u IWT_TMUX_AUTOSTART 2>/dev/null
    eval "$cmd"
  }
  autoload -Uz add-zsh-hook
  add-zsh-hook precmd _iwt-tmux-autostart
fi
`
