package cmd

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

var (
	initIdeaTmux          bool
	initIdeaTmuxAutostart string
	initCompletion        bool
)

var initCmd = &cobra.Command{
	Use:   "init <shell>",
	Short: "Print shell integration (add eval \"$(iwt init zsh)\" to .zshrc)",
	Long: `Print shell integration to stdout. Add to .zshrc:

  eval "$(iwt init zsh)"

This provides:

  Ctrl+O widget   repository picker that opens the selection in IDEA:
                  Enter opens the repository, Tab drills into its
                  worktrees; there Ctrl+N creates a worktree via iwt add
                  for a typed or picked branch, Ctrl+D removes the
                  highlighted one, Ctrl+X prunes merged ones, and
                  Ctrl+H/Esc goes back a level
  Ctrl+G widget   the same navigation, but cd's into the selection and
                  only navigates

Both pick through fzf and are skipped when fzf is absent. Override the
widget keys by setting IWT_OPEN_KEY / IWT_CD_KEY before the eval line.

--idea-tmux adds: inside IDEA's built-in terminal, attach to a tmux
session named after the current worktree, creating it when needed.

--idea-tmux-autostart <cmd> additionally runs <cmd> once in each freshly
created session, right before the first prompt (implies --idea-tmux).

--completion also registers the iwt command completion; the eval line
must then come after compinit in .zshrc (it is skipped silently when
compinit has not run).

Only zsh is supported.`,
	Args: cobra.ExactArgs(1),
	RunE: runInit,
}

func init() {
	initCmd.Flags().BoolVar(&initIdeaTmux, "idea-tmux", false, "attach IDEA's terminal to a per-worktree tmux session")
	initCmd.Flags().StringVar(&initIdeaTmuxAutostart, "idea-tmux-autostart", "", "command to run once in freshly created sessions (implies --idea-tmux)")
	initCmd.Flags().BoolVar(&initCompletion, "completion", false, "also register the iwt command completion (eval after compinit)")
	rootCmd.AddCommand(initCmd)
}

func runInit(cmd *cobra.Command, args []string) error {
	if args[0] != "zsh" {
		return fmt.Errorf("unsupported shell %q (only zsh is supported)", args[0])
	}
	var b strings.Builder
	b.WriteString(zshBase)
	if initIdeaTmux || initIdeaTmuxAutostart != "" {
		extra := ""
		if initIdeaTmuxAutostart != "" {
			extra = " -e IWT_TMUX_AUTOSTART=" + zshQuote(initIdeaTmuxAutostart)
		}
		fmt.Fprintf(&b, zshIdeaTmux, extra)
		b.WriteString(zshAutostartReceiver)
	}
	if initCompletion {
		// Embedded rather than eval'ing "iwt completion zsh" to avoid a
		// second iwt invocation per shell start. compdef only exists
		// once compinit has run, hence the guard.
		b.WriteString("\nif (( $+functions[compdef] )); then\n")
		if err := rootCmd.GenZshCompletion(&b); err != nil {
			return err
		}
		b.WriteString("fi\n")
	}
	fmt.Print(b.String())
	return nil
}

func zshQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

const zshBase = `# iwt zsh integration (generated by "iwt init zsh")

# _iwt-format pads the label fields to a uniform width so the path
# column lines up, and dims the path. fzf --ansi renders the dimming and
# strips the codes from the selected line, and --nth keeps the path out
# of fuzzy matching. Tabs stay as field separators for --delimiter/cut.
function _iwt-format() {
  awk -F'\t' '
    { a1[NR] = $1; a2[NR] = $2; a3[NR] = $3
      if (length($1) > w1) w1 = length($1)
      if (length($2) > w2) w2 = length($2) }
    END {
      for (i = 1; i <= NR; i++)
        printf "%-*s\t%-*s\t%c[2m%s%c[0m\n", w1, a1[i], w2, a2[i], 27, a3[i], 27
    }'
}

# _iwt-branches lists local and remote branch names of a repository,
# deduplicated, as candidates for the new-worktree input box.
function _iwt-branches() {
  {
    git -C "$1" branch --format='%(refname:short)'
    git -C "$1" branch -r --format='%(refname:short)' | sed -n 's#^[^/]*/##p'
  } 2>/dev/null | grep -vx HEAD | sort -u
}

if [[ -o interactive ]] && (( $+commands[fzf] )); then
  # Staged picker shared by both widgets: repositories, then TAB into
  # one repository's worktrees. Esc backs out one level at a time. In
  # "open" mode ($1), CTRL-N creates a worktree via iwt add for a typed
  # or picked branch. Prints the picked path. The repository context
  # lives in shell variables, so a query matching nothing (a new branch
  # name) never loses it.
  function _iwt-pick-staged() {
    setopt localoptions extendedglob
    local mode="$1" out ret key line label repo p q sel branch tty_state
    local verb='cd' expect='ctrl-h' keys2='ctrl-h/esc: back'
    if [[ "$mode" == open ]]; then
      verb='open in IDEA'
      expect='ctrl-h,ctrl-n,ctrl-d,ctrl-x'
      keys2='ctrl-n: new | ctrl-d: remove | ctrl-x: prune merged | ctrl-h/esc: back'
    fi
    while true; do
      out=$(iwt list --repos --porcelain 2>/dev/null | _iwt-format |
        fzf --ansi --height 50% --reverse --delimiter '\t' --nth 1,2 \
          --prompt 'repo> ' --header "enter: $verb | tab: worktrees" \
          --expect=tab)
      ret=$?
      (( ret == 130 || ret == 2 )) && return 1
      key="${out%%$'\n'*}"
      line=""
      [[ "$out" == *$'\n'* ]] && line="${out#*$'\n'}"
      repo="${line##*$'\t'}"
      label="${line%%$'\t'*}"
      label="${label%%[ ]#}" # strip the alignment padding
      [[ -z "$repo" ]] && return 1
      if [[ -z "$key" ]]; then
        print -r -- "$repo"
        return 0
      fi
      while true; do
        out=$(iwt list --porcelain "$repo" 2>/dev/null | _iwt-format |
          fzf --ansi --height 50% --reverse --delimiter '\t' --nth 1,2 \
            --prompt "$label worktree> " --header "enter: $verb | $keys2" \
            --expect=$expect)
        ret=$?
        (( ret == 2 )) && return 1
        (( ret == 130 )) && break # Esc: one level up, back to repositories
        key="${out%%$'\n'*}"
        line=""
        [[ "$out" == *$'\n'* ]] && line="${out#*$'\n'}"
        case "$key" in
          ctrl-h) break ;;
          ctrl-d)
            p="${line##*$'\t'}"
            if [[ -n "$p" ]]; then
              # zle keeps the tty with echo off; restore sane settings so
              # the confirmation prompts show what is typed.
              tty_state=$(stty -g </dev/tty)
              stty sane </dev/tty
              iwt prune "$p" </dev/tty >&2
              stty "$tty_state" </dev/tty
            fi
            continue
            ;;
          ctrl-x)
            (cd "$repo" && iwt prune --merged) >&2
            continue
            ;;
          ctrl-n)
            out=$(_iwt-branches "$repo" |
              fzf --height 50% --reverse --prompt 'new branch> ' \
                --header 'enter: create worktree (type a new name or pick) | esc: back' \
                --print-query)
            ret=$?
            (( ret == 130 || ret == 2 )) && continue
            q="${out%%$'\n'*}"
            sel=""
            [[ "$out" == *$'\n'* ]] && sel="${out#*$'\n'}"
            branch="${sel:-$q}"
            [[ -z "$branch" ]] && continue
            p=$(cd "$repo" && iwt add --no-open "$branch") || continue
            print -r -- "$p"
            return 0
            ;;
          *)
            p="${line##*$'\t'}"
            if [[ -n "$p" ]]; then
              print -r -- "$p"
              return 0
            fi
            return 1
            ;;
        esac
      done
    done
  }

  function iwt-open-widget() {
    local p
    p=$(_iwt-pick-staged open) && [[ -n "$p" ]] && iwt open "$p" >/dev/null
    zle reset-prompt
  }
  zle -N iwt-open-widget
  bindkey "${IWT_OPEN_KEY:-^O}" iwt-open-widget

  function iwt-cd-widget() {
    local p
    p=$(_iwt-pick-staged) && [[ -n "$p" ]] && cd "$p"
    zle reset-prompt
  }
  zle -N iwt-cd-widget
  bindkey "${IWT_CD_KEY:-^G}" iwt-cd-widget
fi
`

// zshIdeaTmux attaches IDEA's terminal to a per-worktree tmux session.
// %s carries the optional autostart handoff (-e IWT_TMUX_AUTOSTART=...),
// applied only when a session is created.
const zshIdeaTmux = `
if (( $+commands[tmux] )) && [[ "$TERMINAL_EMULATOR" == "JetBrains-JediTerm" && -z "$TMUX" ]]; then
  _iwt_session="${${PWD:t}//./_}"
  if tmux has-session -t "=$_iwt_session" 2>/dev/null; then
    exec tmux attach-session -t "=$_iwt_session"
  else
    exec tmux new-session -s "$_iwt_session"%s
  fi
fi
`

// zshAutostartReceiver consumes IWT_TMUX_AUTOSTART once per session. The
// precmd hook defers the command until .zshrc has fully run, so the eval
// line can sit anywhere in it.
const zshAutostartReceiver = `
if [[ -n "$TMUX" && -n "$IWT_TMUX_AUTOSTART" ]]; then
  function _iwt-tmux-autostart() {
    add-zsh-hook -d precmd _iwt-tmux-autostart
    local cmd="$IWT_TMUX_AUTOSTART"
    unset IWT_TMUX_AUTOSTART
    tmux set-environment -u IWT_TMUX_AUTOSTART 2>/dev/null
    eval "$cmd"
  }
  autoload -Uz add-zsh-hook
  add-zsh-hook precmd _iwt-tmux-autostart
fi
`
